### ISSUE TITLE
Showcase alternative solution for component testing

### ISSUE THREAD

**Issue by christian-bromann** [lit/lit.dev#1012]
Currently folks are advised to use [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/) for testing Lit components. Would you be open to also have an alternative solution, e.g. [WebdriverIO](https://webdriver.io/)? It just released component testing primitives and has Lit as one of their [examples](https://github.com/webdriverio/component-testing-examples/blob/main/lit-typescript-vite/src/tests/my-element.test.ts). The onboarding workflow would be much easier as folks only would need to run `npm init wdio@latest ./test` which will walk them through a questionnaire. I would be happy to even further improve this experience by e.g. scanning the project for existing Lit components and pre-generate test files for the user.

I believe WebdriverIO is a good choice for testing Lit components because:
- it doesn't rely on JSDOM and its caveats
- it allows automation through WebDriver which is a web standard for browser automation and mimics user much closer than e.g. JS based clicks
- it offers user to also [switch to Puppeteer](https://webdriver.io/docs/api/browser/getPuppeteer)
- it supports [dependency and module mocking](https://webdriver.io/docs/component-testing/mocking)
- it supports [test coverage reporting](https://webdriver.io/docs/component-testing/coverage)

What do you think?

✌️ Cheers
A WebdriverIO Maintainer 😉

**Comment by christian-bromann** [comment]
Any comments?

**Comment by christian-bromann** [comment]
Thanks for the PR 🙏  take your time, I am happy to answer any questions. I love Lit and we use it a lot within our VS Code extensions at Stateful.

**Comment by christian-bromann** [comment]
@augustjk I want to bring this up to your attention. Is the team interested adding a section how to get started with WebdriverIO + Lit?

**Comment by augustjk** [comment]
@christian-bromann Sorry for letting this stand like this. Absolutely I'd love to showcase wdio as an test option in https://lit.dev/docs/tools/testing/. I'll raise this in our next eng meeting which will be after the holidays so we have consensus among the maintainers.

**Comment by augustjk** [comment]
Hi @christian-bromann
We had a discussion this morning and the team would indeed like to showcase more testing solutions.
Would you be interested in making a PR to add webdriver.io? To make sure things don't go out of sync, we'd like to link out to https://webdriver.io/docs/component-testing/lit/ as the canonical source for usage instruction rather than repeating anything.

**Comment by christian-bromann** [comment]
Thanks @augustjk I will work on a patch asap. I will keep it as simple as possible and will try to mostly reference to the WebdriverIO docs.

**Comment by christian-bromann** [comment]
@augustjk raised a PR in #1287
