### ISSUE TITLE
Event options syntax breaks build

### ISSUE THREAD

**Issue by e111077** [lit/lit.dev#1018]
This PR breaks build #1009 figure out why this is happening so that we can re-commit this

**Comment by augustjk** [comment]
I think the `{{` from the code block is being read as a liquid object.
```js
return html`<button @click=${{handleEvent: () => this.onClick(), once: true}}>click</button>`
```

Perhaps we can add a space between them or modify the code block to be like
```js
const clickEvent = {handleEvent: () => this.onClick(), once: true};
return html`<button @click=${clickEvent}>click</button>`
```

**Comment by e111077** [comment]
Oh LMAO. I wonder if we can escape it instead

**Comment by e111077** [comment]
Or just add a cheeky space between the handlebars

**Comment by justinfagnani** [comment]
Apparently, you can put test inside `{% raw %}...{% endraw %}` tags.

https://shopify.github.io/liquid/tags/template/#raw
