### ISSUE TITLE
Error: Unexpected error

### ISSUE THREAD

**Issue by crgAdrian** [lit/lit.dev#1023]
I encountered the following error on lit.dev:

> Unexpected error
> Error calling GitHub API PATCH /gists/b79f7394a056b65d03c59af213f57eec (HTTP status 422)

Stack trace:
```
Error: Error calling GitHub API PATCH /gists/b79f7394a056b65d03c59af213f57eec (HTTP status 422)
    at y (https://lit.dev/js/components/litdev-playground-page.js:17:396)
    at async C.updateGist (https://lit.dev/js/components/litdev-playground-page.js:27:5527)
```

URL: https://lit.dev/playground/#gist=b79f7394a056b65d03c59af213f57eec
Site version: `prod-73e0861`
Browser: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

**Comment by aomarks** [comment]
Thanks for the report! Did this error go away with a retry, or were you consistently unable to update the gist? Could you describe or copy the specific change you were trying to save to the gist?
