### ISSUE TITLE
sh: 1: wireit: Permission denied 

### ISSUE THREAD

**Issue by BooZaToX** [lit/lit.dev#1024]
I get this error after installing lit.dev and running npm ci & npm run dev:

> lit.dev@0.0.0 dev
> npm run dev:serve --workspace lit-dev-content --watch

> lit-dev-content@0.0.0 dev:serve
> wireit

sh: 1: wireit: Permission denied
npm ERR! Lifecycle script `dev:serve` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: lit-dev-content@0.0.0 
npm ERR!   at location: /media/TOSHIBA/share/develop/lit/lit.dev/packages/lit-dev-content

**Comment by augustjk** [comment]
This sounds like an issue with execution permission for the npm script.

`chmod +x node_modules/.bin/wireit` (might need sudo) could fix this but it probably shouldn't be happening in the first place if npm install is done, and/or npm is run with the right permission.
