### ISSUE TITLE
Incorrect input type on .ts files 

### ISSUE THREAD

**Issue by georgeiliadis91** [lit/lit.dev#1053]
On the rendering section of the docs. 

https://lit.dev/docs/components/rendering/#composing-templates 

On the typescript example there is a miss match of the types of the files.

<img width="745" alt="Screenshot 2023-03-05 at 8 01 37 PM" src="https://user-images.githubusercontent.com/43796963/222977748-31b4afa2-02c7-407c-b9bb-d994d21bbf3c.png">

**Comment by e111077** [comment]
This is valid TS syntax. Funnily enough, TS doesn't allow you to import .ts files, and unfortunately due to how the playground works, imports without `.js` will not work.

So closing this as WAI
