### ISSUE TITLE
Lit dev playground doesn't seem to work for @lit-labs/motion examples

### ISSUE THREAD

**Issue by drk-mtr** [lit/lit.dev#1061]
I've seen these working before, but they don't appear to be loading for me today:

1. Navigate to https://lit.dev/playground/
2. Open the `Sliding Circle` example within the `Motion` section

**Expected:** Loading bar disappears eventually and preview loads in right-hand panel.
**Actual:** Loading bar persists and preview does not appear.

**Comment by augustjk** [comment]
This seems like an issue with the unpkg CDN not being able to serve some dependencies. Hopefully it's a temporary issue but if it persist we may need to look into changing the CDN or serving core deps ourselves.

**Comment by jimaek** [comment]
Consider switching to https://www.jsdelivr.com/
Its production focused with lots of high availability systems and features like API and stats

**Comment by augustjk** [comment]
Playground appears to be working fine now.

**Comment by augustjk** [comment]
I'll close the issue for now. If the unpkg becomes less reliable, we'll need to revisit this. We'd need https://github.com/google/playground-elements/issues/187 to be implemented to swap CDNs.
