### ISSUE TITLE
Add Lit v3.0 prerelease generated API

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit.dev#1111]
### Context

Tracking task to add Lit v3.0 generated documentation to Lit.dev. Does not need to be publicly linked. Can be by URL only.

### Complexity

Naively this is not working because when building with TypeScript, it automatically walks up all parent directories and collects all `@types` encountered. This breaks because `@types/codemirror` on lit.dev is picked up and has incompatible typings with TypeScript 5 and the Lit v3 repo.

References: https://github.com/microsoft/TypeScript/issues/30124 and https://stackoverflow.com/questions/42150920/how-to-block-typescript-2-0-from-walking-up-all-parent-directories-while-resolvi

**Comment by augustjk** [comment]
I found this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64011

Updating to `@types/codemirror@5.60.7` includes above fix so no longer errors on TS 5.
