### ISSUE TITLE
Conflicting info between docs and starter kits

### ISSUE THREAD

**Issue by welingtonms** [lit/lit.dev#1161]
The solution for issue #898 added the "_Don't bundle, minify, or optimize modules_" to the [Tools/Publishing docs](https://lit.dev/docs/tools/publishing/#don't-bundle-minify-or-optimize-modules). 

Although the recommendation is not to bundle/minify, the [TS](https://github.com/lit/lit-element-starter-ts/blob/main/rollup.config.js#L26) and [JS](https://github.com/lit/lit-element-starter-js/blob/main/rollup.config.js#L26) starter kits' _rollup.config_ file includes the `terser` plugin with very specific minification options. This is very confusing as to which one developers should follow.

Which one is correct? Could you please advise?

**Comment by augustjk** [comment]
That's a good point. In this case, the docs on the site are correct and contains our most up-to-date recommendation which is to not bundle, minify, or optimize.

The starter kit repos include a lot of tools and configurations as examples but that can be overwhelming and considered excessive. We've had thoughts about having multiple examples with different levels of complexity, even incorporating into our labs CLI package but so far we've only added a very minimal element starter with `npx @lit-labs/cli init`.

**Comment by justinfagnani** [comment]
The starter kit includes a docs site for the element, and uses Rollup to bundle the JS just for the docs site. That bundle is not published to npm.

**Comment by justinfagnani** [comment]
I think that would be great. It could also go in the README for both the static site and bundling sections. We would greatly appreciate a PR for that!

**Comment by welingtonms** [comment]
Hi @justinfagnani @augustjk, I just submitted the [PR for the JS starter project](https://github.com/lit/lit-element-starter-js/pull/36). Would you mind having a look? If everything looks okay, I'll do the same for the TS project.

Please let me know your thoughts,
Thanks!
