### ISSUE TITLE
Lit labs graduation blog post

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit.dev#1165]
https://docs.google.com/document/d/1z5DqGtkh5Ky88Dczc3QQh53qxr8EPkdwU7Wujn8d1Wo/edit#heading=h.mqbvi8g6hzd8

**Comment by AndrewJakubowicz** [comment]
This is drafted up here: https://github.com/lit/lit.dev/pull/1196/commits/08e26aa6a8b2ec474cb6a7ecd175883f53e75df6

Closing this issue, as I think this is now related to the main Lit 3.0 release blog post.
