### ISSUE TITLE
Can't run the lit.dev project.

### ISSUE THREAD

**Issue by zh-lx** [lit/lit.dev#1245]
There are lots of users of lit from China, so I forked the repository and want to translate docs to a Chinese version. But I failed in the first step because I can't run this project.

After I run `npm ci` and `npm run dev`, the following error will be throwed in the terminal:

<img width="795" alt="image" src="https://github.com/lit/lit.dev/assets/73059627/7bf46ac0-cf9d-43f8-ae51-7f8f1b154af5">

I think maybe the readme of this project a little old. Could you please update the readme?

**Comment by augustjk** [comment]
That's odd. `npm run dev` from the root directory does work for me. Assuming `npm ci` was done already, what version of `npm` are you on? The only reason I can think of for this error is that it's not recognizing the `--workspace` flag which was added in some version of npm v7. I'm on npm v9 and I think some members of our team are using v10.

There's been a community member who also wanted to do a Chinese translation here too: https://github.com/lit/lit.dev/pull/817
Unfortunately we haven't been able to move forward on a sustainable approach to adding localization for the site https://github.com/lit/lit.dev/issues/355

**Comment by zh-lx** [comment]
Thank you for your answer, my npm version is v6. It can work now after I upgraded my npm version.

**Comment by AndrewJakubowicz** [comment]
Closing as it looks like the issue has been resolved. Please re-open if anything else comes up!
Thank you!
