### ISSUE TITLE
createProperty() is deprecated warning

### ISSUE THREAD

**Issue by MaartenPetiet** [lit/lit.dev#1300]
I am overriding the `createProperty` method to automatically convert all properties to kebab-cased attributes. This should be possible according to these docs: https://lit.dev/docs/api/ReactiveElement/#ReactiveElement.createProperty

However, I get the following console warning when I use it: Overriding ReactiveElement.createProperty() is deprecated. The override will not be called with standard decorators See https://lit.dev/msg/no-override-create-property for more information.

This links to a page that returns a 404.

What is the correct status of this functionality? And if it is indeed deprecated, what would be the correct way to automatically convert property names to kebab-cased attributes?

**Comment by augustjk** [comment]
Sorry for the missing docs. It's on our radar to address https://github.com/lit/lit.dev/issues/1262

In the mean time, please see the answer here for some context on `createProperty()` deprecation and alternative: https://github.com/lit/lit/discussions/4434#discussioncomment-7779910

**Comment by MaartenPetiet** [comment]
@augustjk okay thank you for your quick reply. I will look into that!
