### ISSUE TITLE
Documentation on expressions should be updated

### ISSUE THREAD

**Issue by fireflysemantics** [lit/lit.dev#1361]
[In the documentation on expressions](https://lit.dev/docs/templates/expressions/) it says the following:

> You might also want to remove the attribute if the value is not truthy so that values of false or empty string '' remove the attribute

Empty string `''` is truthy.  So an empty string will leave the attribute in place.

This is the demo snippet in the documentation.

```
html`<button aria-label="${this.ariaLabel || nothing}"></button>`
```

This will leave the attribute in place if `ariaLabel=''`.

https://stackblitz.com/edit/vitejs-vite-d25wmw?file=package.json

**Comment by augustjk** [comment]
[Empty string is falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) and as such it the code snippet correctly falls back to `nothing` when using `||`, therefore removing the attribute.
See this [playground example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgbm90aGluZ30gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG4gIFxuICBlbXB0eVN0cmluZyA9ICcnO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxwXG4gICAgICAgIGZvbz0ke3RoaXMuZW1wdHlTdHJpbmcgfHwgbm90aGluZ31cbiAgICAgICAgYmFyPSR7dGhpcy5lbXB0eVN0cmluZ31cbiAgICAgID5IZWxsbywgJHt0aGlzLm5hbWV9ITwvcD5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0). If you inspect the `<p>` element, `foo` attribute does not exist, but `bar` does.

I also do not see any attribute on the `<button>` element in the provided stackblitz example either.

**Comment by fireflysemantics** [comment]
@augustjk good catch .... I got my wires crossed ... :)
