### ISSUE TITLE
Draft blog text for release

### ISSUE THREAD

**Issue by nicolejadeyee** [lit/lit.dev#157]
Blog posts
#1228 P0 - Announcing the Lit brand
Consolidated our libraries into one org
Move away from polymerlabs
Can link to the more technical lit 2.0 release
This blog will be our Hallmark post
#1229 P0 - Lit 2.0 release
New features, changes, etc.
P1 - Lit-SSR
Mention it in the Lit 2.0 release, but there should be an announcement for the pre-release

**Comment by aomarks** [comment]
Fixed by https://github.com/lit/lit.dev/pull/328
