### ISSUE TITLE
Related libraries—Finish Standalone lit-html section

### ISSUE THREAD

**Issue by arthurevans** [lit/lit.dev#23]
- Add intro, explaining that lit-html can be used independently of web components or LitElement to render DOM anywhere in the page.

- Fill in missing content. In particular, probably restructure a bit to clarify where the context comes from when using lit-html standalone, and how the examples differ from the LitElement based examples.
 
- Edit & clean up.

**Comment by aomarks** [comment]
Looks pretty done to me: https://lit.dev/docs/libraries/standalone-templates/
