### ISSUE TITLE
Add slack redirect to lit.dev

### ISSUE THREAD

**Issue by arthurevans** [lit/lit.dev#339]

**Comment by Vac1911** [comment]
Just heard about lit and wanted to join the slack community. Currently the invite links seem to be not working. ![image](https://user-images.githubusercontent.com/45333542/115762960-0034ed80-a372-11eb-9d25-c9be9bd3182a.png)

**Comment by arthurevans** [comment]
That looks like the normal invite link. Are you unable to join after signing in? Were you a member of the Polymer slack previously? (It's the same slack org, just renamed, so if you were already in the community you'd just see a sign in rather than a Join message IIRC.)
