### ISSUE TITLE
RefOrCallback link does not lead to API docs

### ISSUE THREAD

**Issue by Christian24** [lit/lit.dev#344]
Hello,

On the page about builtin directives (https://lit.dev/docs/api/directives/#ref) the link for `RefOrCallback` does not lead to the API for `RefOrCallback`. It instead just leads to the top of the page.

**Comment by AndrewJakubowicz** [comment]
Thank you! This has been addressed. https://lit.dev/docs/api/directives/#RefOrCallback now links correctly.
