### ISSUE TITLE
TS and JS starter kits linked in docs are outdated

### ISSUE THREAD

**Issue by Christian24** [lit/lit.dev#345]
Hello,

The Starter Kit menu item in the docs (https://lit.dev/docs/tools/starter-kits/) links to the master branches of the TS and JS starter kits. Those are not yet updated for lit 2.0. Either merge the `lit-next` branches into master or change the links to the `lit-next` branch.

Thanks,
Christian

**Comment by ptrwis** [comment]
+1
I don't even know how to create new project in Lit2 :) Projects downloaded from Playground don't have TS config or npm build/run scripts. In Angular I was just using ng cli for everything  ¯\_(ツ)_/¯

**Comment by aomarks** [comment]
Fixed by https://github.com/PolymerLabs/lit-element-starter-js/pull/16 and https://github.com/PolymerLabs/lit-element-starter-ts/pull/47
