### ISSUE TITLE
Upgrading JS setup to Lit

### ISSUE THREAD

**Issue by xiki808** [lit/lit.dev#365]
Took me a little while to get my upgrade to work, from LitElement to Lit.

My setup is based on JS, and I was following the [Upgrade Guide](https://lit.dev/docs/releases/upgrade/), which I feel it doesn't focus on JS as much as it does with TS, actually the whole Lit project documentation. I'm feeling dodgy to keep using Lit because of this. I'm not willing to make the switch to TS. How much will the Lit project take care of JS developers in the future - including documentation?

Most probably I'm not getting the whole idea, but would like someone to elaborate more why this project is focused more on TS.

After npm install 'Lit' in my webpack setup, I was getting a `export 'LitElement' was not found in 'lit'` warning and other errors. After some search I found this [example](https://github.com/PolymerLabs/lit-element-starter-js/blob/master/package.json), which shows that I also need specifically `lit-element@3.0.0-rc.1`. Why do I need both packages?

After getting it to work, I was anyhow quite happy as importing just both LitElement and html, is now around 1kb less than before.

Also one more thing, most likely a silly question.. but I didn't manage to use decorators in my JS setup, even after including `@babel/plugin-proposal-decorators`. Can I use decorators in JS or are these only for TS?

Much Thanks!

**Comment by aomarks** [comment]
See also https://github.com/lit/lit.dev/issues/332 for tracking adding a global JS/TS switch

**Comment by xiki808** [comment]
Thanks for your reply @justinfagnani the docs are anyhow very helpful for JS development but also it is very important as only few results are found on Google regarding a Lit related issue.

**Comment by aomarks** [comment]
Closing as we should now show all examples in both JS and TS, with a global switch, and our prose should be written in a neutral way too.
