### ISSUE TITLE
Documentation: Add search

### ISSUE THREAD

**Issue by lazka** [lit/lit.dev#367]
Having a search feature built into the docs would be nice. I'm struggling to locate things and usually have to click through multiple pages each time.

Example:

* Search for "unsafeHTML"
* https://lit.dev/docs/templates/directives pops up as a suggestion

**Comment by AndrewJakubowicz** [comment]
An initial implementation of site search on lit.dev is now live behind a feature flag!

You can use it by adding the `?mods=search` query parameter, i.e: https://lit.dev/?mods=search
This query param makes a search input appear in the site navigation.

We hope it will make it easier to find useful information in the documentation and api.
Also a big thanks to these two great libraries: MiniSearch and the Lion combobox component!

If you find any issues or have feedback, please don't hesitate to share it here.

Thank you

**Comment by AndrewJakubowicz** [comment]
With #435 merged this is now live. Thank you!

**Comment by lazka** [comment]
Thanks!
