### ISSUE TITLE
Zero-width spaces break copy-pasted code

### ISSUE THREAD

**Issue by azangru** [lit/lit.dev#380]
If somebody copies a code snippet from lit.dev homepage, like I just did:

![image](https://user-images.githubusercontent.com/6834224/118737889-b2f74f00-b83d-11eb-8c86-e9034415bcc7.png)

paste it in their code and try to run it, they may be puzzled by the error that they will see from their build tools:

![image](https://user-images.githubusercontent.com/6834224/118737987-e803a180-b83d-11eb-8e15-44fccba3aea0.png)

It may not be immediately obvious to that person (like it wasn't for me) that the error is caused by the ZeroWidthSpace character that resides in the blank lines of the snippet and is an illegal white space character in typescript code:

![image](https://user-images.githubusercontent.com/6834224/118738163-4c266580-b83e-11eb-9f78-30b2102ae687.png)

Not sure if this is a real issue, but it might be a cause of some consternation for the developer.

**Comment by AndrewJakubowicz** [comment]
Thank you for this issue and providing excellent details.
I've deployed a fix that should resolve this.

Closing issue now as it should be fixed. Let me know if the issue persists.
