### ISSUE TITLE
Inform user that ServiceWorkers are not available when they are not available

### ISSUE THREAD

**Issue by e111077** [lit/lit.dev#400]
FF will disable ServiceWorkers on FF ESR builds and in-private browsing. Probably be useful to tell the user that ServiceWorkers are not available and probably give them some troubleshooting tips

source: https://bugzilla.mozilla.org/show_bug.cgi?id=1383256

**Comment by arthurevans** [comment]
Probably in @aomarks wheelhouse here, since this'll break the playgrounds.

**Comment by aomarks** [comment]
This was done in https://github.com/google/playground-elements/pull/224
