### ISSUE TITLE
Redirect lit-html.com to the lit-html docs site

### ISSUE THREAD

**Issue by jbingham** [lit/lit.dev#447]
## Initiative / goal
We now have the lit-html.com domain!
It doesn't point anywhere :/

### Scope
Figure out DNS settings to redirect to the current docs site

## Acceptance criteria and must have scope
Typing lit-html.com into a browser redirects to the current docs site

**Comment by aomarks** [comment]
Probably no reason to do this now given that we've moved to lit.dev
