### ISSUE TITLE
Docs: Inheriting styles from a superclass doesn't show an es5 compatible option

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit.dev#475]
### Context

In the section [Inheriting styles from a superclass](https://lit.dev/docs/components/styles/#inheriting-styles-from-a-superclass) we show an example of using the super classes style with `super.styles` syntax.

```typescript
// Minimal example
class SuperClass {
  static get styles() {
    return ['style'];
  }
}

class ChildClass extends SuperClass {
  static get styles() {
    // On ES5, error here: `Only public and protected methods of the base class are accessible via the 'super' keyword.`
    return [...super.styles, 'additional style'];
  }
}
```

See example in [typescript playground (ES2020)](https://www.typescriptlang.org/play?target=7#code/KYDwDg9gTgLgBAbwL4G4BQaD0Aqba7ZwAqEcUwYUEAJgK4DGwcABgM61jBQB0rMAngBtgrZnACWrdsAA0ceoPH0A1nABERAMpwAwhAB2AM3EBzNXGpUw1CAHd93fIR0ALAIb6TTDW6heY5jCkagCimgCsao4EmBhoCm5ScJocXDqCiayI+HB8bjBKcP65AsKsABQAlNlwtWTAMLRQ+nAA2gDkfELA7QC66LVIaEPxGUmu4oLU6ZlwoDDA+tRZKZxQM0kIOXkF9EUNJd0V1Vt1cJiYcADyLWHhclxUUHAuXMAAXCw3gvxwYLQAI0Uew81D+VAW9AWYIAtg0XDQshBDHAYK84ADEkwEklfEw3PRGFJxECmAA3cRuVHozqpKDtODKYD8WzQajcZg5WrkRrNNrcAXsNa8UoiOTtNzUajiAoGNyCQ7CPoDOBDIZAA), and [same code with target set to ES5](https://www.typescriptlang.org/play?target=1#code/KYDwDg9gTgLgBAbwL4G4BQaD0Aqba7ZwAqEcUwYUEAJgK4DGwcABgM61jBQB0rMAngBtgrZnACWrdsAA0ceoPH0A1nABERAMpwAwhAB2AM3EBzNXGpUw1CAHd93fIR0ALAIb6TTDW6heY5jCkagCimgCsao4EmBhoCm5ScJocXDqCiayI+HB8bjBKcP65AsKsABQAlNlwtWTAMLRQ+nAA2gDkfELA7QC66LVIaEPxGUmu4oLU6ZlwoDDA+tRZKZxQM0kIOXkF9EUNJd0V1Vt1cJiYcADyLWHhclxUUHAuXMAAXCw3gvxwYLQAI0Uew81D+VAW9AWYIAtg0XDQshBDHAYK84ADEkwEklfEw3PRGFJxECmAA3cRuVHozqpKDtODKYD8WzQajcZg5WrkRrNNrcAXsNa8UoiOTtNzUajiAoGNyCQ7CPoDOBDIZAA).

Changing the target to ES5 causes a compile error.

### Possible solutions

Show an alternative example if ES5 target is required.

```typescript
class ChildClass extends SuperClass {
  static get styles() {
    // Using SuperClass directly works on ES5 & ES2020
    return [...SuperClass.styles, 'additional style'];
  }
}
```

**Comment by rictic** [comment]
Related TypeScript issue: https://github.com/microsoft/TypeScript/issues/45712

**Comment by arthurevans** [comment]
Just to make sure I understand correctly: this is an issue with TypeScript, right? It appears that if you write this code in a JS file and transpile it with Babel, it _should_ work correctly:

[Babel playground](https://babeljs.io/repl/#?browsers=ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PTAEFkEsDtIWwIYBtQFMAeC4AcmoFADGSCAzqaAMoCu2qATgMInmgDe-oopALgj5EKgA5qh7ceATzykAFAEp2nLqHpjq9aKADaAcl7TUugLoBuZQF98VoiwqMAFpCQATZmQoYeqaC4o06JjslLl5-QRExCUM5RQ4VUBBQAHktAFFKAFYAGjR6egB7elAHBlQALlAAA1SkSVBsagAjJAiEXwbC70JvF1A4MQcCv1ACgDNQHlLQJrJUUGIPUAQ1ZcJCVHJIFvmAN0gESen9WgZdUABrVEkAdyKXADoq5S41Hg0tbQfv0lP6B4MMlyugQLhckAEBWgyGieBM5i4VisQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.7&externalPlugins=&assumptions=%7B%7D)
