### ISSUE TITLE
Error in documentation (Typescript) for inheriting-styles-from-a-superclass

### ISSUE THREAD

**Issue by davie-robertson** [lit/lit.dev#523]
https://lit.dev/docs/components/styles/#inheriting-styles-from-a-superclass

`super.styles,`

gives the following error

`'super' property access is permitted only in a constructor, member function, or member accessor of a derived class.`

**Comment by AndrewJakubowicz** [comment]
Thanks for the issue, transferred to the lit.dev documentation site repository.

The preview is currently broken:

https://user-images.githubusercontent.com/15080861/134965647-cb8b9b6f-6168-45d7-9245-3be538495d6f.mp4

**Comment by davie-robertson** [comment]
thanks
