### ISSUE TITLE
Update documentation about what various falsy values render

### ISSUE THREAD

**Issue by nkabrown** [lit/lit.dev#565]
Documentation for [Rendering nothing](https://lit.dev/docs/templates/conditionals/#rendering-nothing) in the Conditionals section and the comments for `unsafeHTML` and `unsafeSVG` need to be updated to reflect the fact that `undefined`, `null`, and the empty string no longer render an empty text node but similar to `nothing` do not render a node.

See [issue 1559](https://github.com/lit/lit/issues/1559) in the lit repository and various comments like "Rendering the value `nothing`, `null`, or `undefined` in the `unsafeHTML` or `unsafeSVG` directive will now result in no content being rendered (previously it would render `'[object Object]'`, `'null'`, or `'undefined'`, respectively)." from the upgrade guide and "In child expressions, `undefined`, `null`, `''`, and `nothing` all behave the same and render no nodes." from [lit-html lines 351-352](https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L351-L352).

**Comment by sorvell** [comment]
Quick update on this:
* We're planning to clarify these docs and add info about using `nothing` either in a child or attribute expression.
* We're electing to explain `nothing` more explicitly in favor of offering more directives like `ifDefined`. In particular, there's a lot of flexibility in just doing: `value ?? nothing` or `value || nothing`.
