### ISSUE TITLE
Expand lit labs page to more clearly indicate status

### ISSUE THREAD

**Issue by aomarks** [lit/lit.dev#642]
The https://lit.dev/docs/libraries/labs/ page is currently very minimal, and doesn't give a clear indication of the readiness of each library.

We should expand this page to more clearly indicate the status of each library.

Maybe also find or create a GitHub discussion page for each one where we can invite feedback, and link those.

Could also consider a scheme suggested by @e111077 to come up with a structured scheme for describing the status of each library, RFC style.

**Comment by e111077** [comment]
pretty sure you can make github discussion categories so multiple discussions can take place

**Comment by augustjk** [comment]
Completed with https://github.com/lit/lit.dev/issues/839
