### ISSUE TITLE
[docs] "Updates?" in shouldUpdate

### ISSUE THREAD

**Issue by vlilloh** [lit/lit.dev#650]
I've made several checks with method `shouldUpdate`, and property changes inside this method do **not** trigger an element update, but the parameter `changedProperties` itself of `shouldUpdate` is updated synchronously in the same element update.

So I think the field "Updates?" of this method in this [doc](https://lit-element.polymer-project.org/guide/lifecycle#shouldupdate) is wrong. It should says:

> **Updates?** | No | Property changes inside this method will not trigger an element update.

**Comment by justinfagnani** [comment]
You really shouldn't be changing properties in `shouldUpdate()` anyway. Should we say that?

**Comment by arthurevans** [comment]
Perhaps, but the same is true for `willUpdate`, where we *do* recommend they change properties.

I can add a note about not changing properties in `shouldUpdate()` (Although one could perhaps imagine a situation in which a  new property value naturally falls out of the `shouldUpdate` calculation, in which case it'd be silly to compute it twice ...? Maybe I'm just borrowing trouble here, IDK.)
