### ISSUE TITLE
Document usage of svg tagged template literal

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit.dev#652]
### Context

There seems to be minimal documentation on the usage and constraints of the `svg` tagged template literal (TTL).

### Why

The `svg` tagged template literal is not a synonym for `html` and there doesn't appear to be any documentation around `svg` usage.

For example. A complete `<svg>` element should be within an `html` TTL. Whilst a piece of svg, like a `<rect>` would be a candidate for the svg TTL. Another corner case is returning an `svg` tagged template literal from `render()` doesn't imply svg composition. `render()` wraps the svg in a web component, and it is no longer possible to use the svg partial within an svg element.

### Acceptance criteria

 - Document `svg` usage in Lit.
 - Is it an error to return an `svg` TTL from `render()`?
 - Apply Justin's feedback & maybe codify it in dev mode: https://github.com/lit/lit/pull/2479#discussion_r799829808

**Comment by justinfagnani** [comment]
I think along with https://github.com/lit/lit/pull/2479 we should mention the `svg` tag in the guide. cc @arthurevans
