### ISSUE TITLE
How to handle mutable object should be more clear

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit.dev#694]
We've heard that it is sometimes not clear how objects are handled across ReactiveElement and lit-html with respect to change detection.

By default, ReactiveElement property setters only request an update of the new value is not identical to the old value, so if you mutate an existing object, ReactiveElement will not re-render. You can handle mutable objects by overriding `hasChanged` to be `() => true`. You can also use an immutable pattern to changes are expressed as new objects.

Our example of `hasChanged` uses a string value, which might not be the most common case. We also don't seem to talk about this concern either independently enough or high enough on the reactive property page.

And it might be important to note that lit-html has different behavior: it assume objects may have change and only bails on updating the DOM (attributes, text, or properties) when _primitives_ are equal. `live()` might be part of this topic too.

**Comment by arthurevans** [comment]
Yeah, I have been meaning to get back to the section on reactive properties for just this reason.
