### ISSUE TITLE
Document that Boolean attributes should never be initialized to true if they should be configurable from markup

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit.dev#744]
### Context

This is an area of confusion and we don't have clear documentation on lit.dev relating to this case.

Initializing a boolean attribute to `true` results in confusing behavior, as you cannot declaratively remove the attribute that has been defaulted to true from markup.

### Proposal

Add a warning or note to https://lit.dev/docs/templates/expressions/#boolean-attribute-expressions stating that boolean attributes should never be default initialized to true.

### References

This has been discussed in the past:

- Kevin's comment: https://github.com/Polymer/polymer/issues/1812#issuecomment-112226630
- Link to polymer documentation that explains the same issue: https://polymer-library.polymer-project.org/2.0/docs/devguide/properties#configuring-boolean-properties

Out of scope of this issue, but maybe this can be caught by the analyzer.

**Comment by arthurevans** [comment]
This just came up in a chat conversation today, as well. I think it's really more apropos to the Reactive properties section, because it's really about the attribute API of a given component. We don't really talk much about API patterns at the moment.
