### ISSUE TITLE
[tutorial] @eventName reference on intro-to-lit/03 confusing

### ISSUE THREAD

**Issue by grayside** [lit/lit.dev#753]
### Problem
On https://lit.dev/tutorial/#03 there is a bit of text:

```
@eventName is a special syntax for adding an event handler using an expression.
```

This is not explained anywhere in the page, the referenced Event page, or the solution.

### Impact

This was a distraction that led to taking a few extra minutes trying to figure out how to follow the steps on the page.

**Comment by arthurevans** [comment]
Thanks for the report. The sentence is supposed to explain the step you've just done, and obviously it didn't work.

Before I try to improve the wording, can you add a little more detail about what was confusing? 

 For example, was it unclear that the _eventName_  `@eventName` was a placeholder? Or was there something else about the sentence that didn't make sense?

**Comment by grayside** [comment]
I thought `@eventName` was a literal directive like `@property` that I was meant to place above something. I don't really understand how the @property annotation is used as I'm not familiar with that syntax.

I wasn't sure which of the following was intended:

### Confusion:
```
@eventName
@input=${this.changeName}
```

### Maybe it was for the next instruction?
```
@eventName
changeName(event: Event) {
  const input = event.target as HTMLInputElement;
  this.name = input.value;
}
```

### Big confusion
```
@eventName
    return html`
      <p>Hello, ${this.name}</p>
      @input=${this.changeName}
      <input @input=${this.changeName} placeholder="Enter your name">
    `;
```

**Comment by arthurevans** [comment]
Ack! Yeah, that would be super confusing. And re-reading the step it says to add the "@input" expression "inside the tag" which is a little too vague.

Here's a rewrite:

Find the input element and add a declarative event listener:

```
<input @input=${this.changeName} placeholder="Enter your name">
```

This `@input` expression adds `this.changeName` as an event listener for the `input` event. (You can use this syntax for any event listener—just replace `input` with any event name and `this.changeName` with any JavaScript expression that evaluates to an event handler function.)
