### ISSUE TITLE
[infra] dev command parallelization issue with wireit

### ISSUE THREAD

**Issue by augustjk** [lit/lit.dev#782]
https://github.com/lit/lit.dev/blob/636a3823d93837989c1aa8927189af34f72dacc6/package.json#L15

The two commands being run in parallel here both use `wireit` and have dependencies specified that overlap. Since two instances of `wireit` are running, some dependent scripts end up being run twice leading to issues like this where `build:samples` is being run twice, one succeeding and one failing.
![image](https://user-images.githubusercontent.com/40413829/165408311-f4e6b353-89dc-49c2-9815-f3c864f5d65d.png)

Perhaps a fix for this would be instead to use `&`, just have a single `wireit` script that runs the two separate watch scripts so `wireit`'s dependency resolution will dedupe?

**Comment by aomarks** [comment]
I think @rictic was running into this too.

https://github.com/google/wireit/issues/35 is related -- each script should have a lock file which prevents wireit invocations from fighting each other. In this case, whichever one started first would get to finish, while the second waits for the lock to be released. Then the second one would notice the build is already fresh and skip.

**Comment by arthurevans** [comment]
@rictic that sounds good... how would we do this?

I am profoundly ignorant of wireit, but the dev mode is REALLY broken now and it's costing us a lot of time.

**Comment by AndrewJakubowicz** [comment]
Elliott has made this more robust https://github.com/lit/lit.dev/pull/803! Thank you @e111077 !!!!!

**Comment by aomarks** [comment]
I believe this is fixed by https://github.com/lit/lit.dev/pull/809 via https://github.com/google/wireit/pull/189.

`npm run dev` at the top-level should now do all the right things.

Don't forget to do an `npm ci` after pulling this change, because it requires the latest version of Wireit.
