### ISSUE TITLE
[react examples] TSX <--> JS functionality is broken

### ISSUE THREAD

**Issue by taylor-vann** [lit/lit.dev#890]
TSX files in the React examples do not currently transpile to JS files when requested.

To close this bug, allow the user to switch between TSX and JSX. If that transpilation is not possible, then TSX to JS would be an alternative.

**Comment by justinfagnani** [comment]
I believe this should work by using `jsx: 'preserve'` when running the custom TS compiler setup. cc @aomarks

**Comment by augustjk** [comment]
Fixed by #905
