### ISSUE TITLE
[labs/context] lit.dev documentation

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit.dev#952]
We need docs for context ([README](https://github.com/lit/lit/tree/main/packages/labs/context#readme)).

One big question is where the docs should live: in In "Related Libraries", under "Components" in a data/communication page/ Both?

cc @benjamind @arthurevans

**Comment by hfl0506** [comment]
@justinfagnani  Just want to ask about the document refer to lit/context, will you guys provide example of using context and context setter in child component or nested child component? Thank you

**Comment by arthurevans** [comment]
@hfl0506 have you looked at the docs in the README? https://github.com/lit/lit/blob/main/packages/labs/context/README.md

I don't think you should need to use events directly if you're using the context package, but I may be missing a detail here.

**Comment by hfl0506** [comment]
I have read the docs in the README, but my problem is I want to update the context value in the grandchild component.
For example I have set the provider at app.ts
```ts
private pathProvider = new ContextProvider(this, globalPathContext, {
    path: '',
  });
  public setGlobalPath(newPath: GlobalPath) {
    this.pathProvider.setValue(newPath);
  }
```
how can I use the setter for component which under the app component ?

**Comment by arthurevans** [comment]
Sorry for the delay, I've been out for a bit, just coming back to this issue.

Do you mean you want the grandchild component to be able to update the context for all consumers?

If so, there's no built-in way to do this. As I understand it, the context protocol is only designed to solve the problem of providing data down the tree. See https://github.com/webcomponents-cg/community-protocols/blob/main/proposals/context.md for more background.

It sounds like what you're looking for is more like a state management solution, like Redux, but perhaps that's overkill for what you're trying to do.

So, a couple of possible approaches:

Have the grandchild fire an event, like:

```
this.dispatchEvent(
  new CustomEvent('update-context', { 
    bubbles: true,
    composed: true,
    detail: newContextValue
  })
);
```

And have the grandparent receive the event and update the context. 

Alternately, you could have the context provider provide a Redux store, and have the grandchild dispatch actions to the store.

**Comment by hfl0506** [comment]
> 

Sorry for late notice, I had done the approach as you mention in my project as well. 
I was wondering is that me misunderstanding the docs or else in the beginning.
Anyway, Thank you very much for your help, really appreciate it.

**Comment by justinfagnani** [comment]
Fixed by https://github.com/lit/lit.dev/pull/1037
