### ISSUE TITLE
[docs] In (not the most recent) Safari on desktop search field covers the header

### ISSUE THREAD

**Issue by jrencz** [lit/lit.dev#980]
Hi!

I noticed that the site doesn't work the same in Safari as it does in Chrome:

<img width="1388" alt="Screenshot 2022-10-17 at 12 19 33" src="https://user-images.githubusercontent.com/948356/196153464-cf047e02-b568-4764-88f6-238bc109fa13.png">

<img width="1388" alt="Screenshot 2022-10-17 at 12 19 50" src="https://user-images.githubusercontent.com/948356/196153491-5224c03b-46ff-429f-814a-65153b9e15bd.png">

Screen above taken on safari 14 (yeah, I know it's ancient)
<img width="396" alt="Screenshot 2022-10-17 at 12 21 57" src="https://user-images.githubusercontent.com/948356/196153795-a180e884-1eb0-46c6-afca-1335bb232f34.png">

Here's 15 TP
<img width="1388" alt="Screenshot 2022-10-17 at 12 23 22" src="https://user-images.githubusercontent.com/948356/196154071-bfbee906-999b-4613-8542-eb0e0a9850bb.png">

but I also checked on Ventura beta (where it's 16) and in that version it doesn't look OK either
I don't have that mac by me right now, I'll post details later today.

There are no errors in console, though.

**Comment by e111077** [comment]
Heya, thanks for the detailed report! Unfortunately the native HTML `<dialog>` element is available on Safari 15.4. Current stable version of Safari is 16.0 (16.1 TP on Monterey).

On lit.dev we try to follow "last 2 version" rule which includes Safari 15.4 now.

Though your points points about safari 15 TP and ventura beta are concerning. Can you please provide me with the version numbers of those browsers?

**Comment by jrencz** [comment]
It's OK on 16.1, which means I must have been under impression from the main machine I work on where I keep the old system for various reasons (ah, those corporate VPNs)

<img width="1488" alt="Screenshot 2022-10-17 at 22 36 03" src="https://user-images.githubusercontent.com/948356/196278131-9b5aaa16-ab2a-43ac-818f-88b05c4d94fc.png">

<img width="396" alt="Screenshot 2022-10-17 at 22 36 04" src="https://user-images.githubusercontent.com/948356/196278173-03aafdfc-d6a0-4d1c-8572-90de1263fc6e.png">

> On lit.dev we try to follow "last 2 version" rule which includes Safari 15.4 now.

Sure, I understand.
Nevertheless maybe let's hide it, if it's not usable and it hides away other parts. I'm thinking something like:

```css
@supports not selector(:modal) {
    litdev-search-modal {
        display: none !important;
    }   
}
```

which I guess will do the job (guess, because at the moment I'm writing from the other, Ventura mac)

**Comment by dman777** [comment]
@e111077  This issue exists for me on my laptop with Chrome Version 99.0.4844.51 (Official Build) (64-bit) on Ubuntu 20.04 LTS. It does not exist on my desktop, which is also Ubuntu.
